### ISSUE TITLE
Negative movement restriction

### ISSUE THREAD

**Issue by asyinka** [asyinka/keyPresses#1]
ISSUE YET TO RESOLVE Pressing the arrow keys at the initial stage of 0px can push the box away from the body of the webpage and so one who inadvertently presses the arrow keys may find the page empty. A conditional statement to restrict the negative movement of the box to position 0 i.e if x == 0, x should not move in a negative direction same as y; Kindly assist with this code; @cremirdevio

**Comment by josephajibodu** [comment]
Okay I will check it out. Glad you are using GitHub properly.

I will fork it and create a PR for you to review and merge.

You would see how my PR will be created such that once you merge my PR, it will automatically close this issue.
